### PR TITLE
Fix nested enum models generation

### PR DESCRIPTION
**Pull request by fullkomnun**
Fixed a couple of issues with generation of enum classes that are nested within data classes

### CODE REVIEW

**Comment by cromefire** [comment]
Do you have a test file for this?

**Comment by fullkomnun** [comment]
I tested it with a real API that i'm using, how do you suggest to test this?

**Comment by fullkomnun** [comment]
There's the classic ['petstore.yaml'](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml) for which the nested enums are generated properly.
However, apparently there's an **unrelated** issue with the wrapping list/map requests/responses which i'm looking into.

**Comment by cromefire** [comment]
> There's the classic ['petstore.yaml'](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml) for which the nested enums are generated properly.

Okay will check, might take a few days.

> However, apparently there's an **unrelated** issue with the wrapping list/map requests/responses which i'm looking into.

The map/list issues have been broken all the way, so to say a known issue, but I'm still not a 100% sure how to fix that. Originally those models just extended Map and List, but they are final, so it's just not working at all, I think currently I just don't generate those, which... isn't ideal... I'll add that to the TODOs if that didn't already happen and will think of something

**Comment by fullkomnun** [comment]
I submitted a separate PR with suggested solution to request/response array/map wrappers.

**Comment by cromefire** [comment]
Fixed

**Pull request closed without merging**
