### PR TITLE
Fix request response collection wrappers

### PR DESCRIPTION
**Pull request by fullkomnun**
Fixed issues that manifested with ['petstore.yaml'](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml) when request/response
are wrappers of array/map.

If we ["prefer lists to arrays"](https://stackoverflow.com/a/36263748) which is reasonable for Kotlin
we can drop these wrappers altogether making generation simpler 
(serialisation doesn't work out-of-the-box of arrays but does for lists).

### CODE REVIEW

**Comment by cromefire** [comment]
You didn't handle decoding of mixed stuff yet, right?

I've seen classes, where it generated something like (simplified; out of my memory)
```kotlin
data class Xyz(val test: String) : List<Int>
```

**Comment by fullkomnun** [comment]
Which use-case are you referring to by "mixed"?

**Comment by cromefire** [comment]
It seems to be a kind of data class like usually, but all remaining properties (I might have been wrong with the list because that doesn't work it was a map I think) are stuffed into a map, not great API design, but seems to be the case for some apis

**Comment by cromefire** [comment]
I'll try to get you an example

**Comment by cromefire** [comment]
Here's the example:
```kotlin
@Suppress("ArrayInDataClass")
@Serializable
public data class ProblemDetails(
    @SerialName(value = "type")
    val type: kotlin.String? = null,
    @SerialName(value = "title")
    val title: kotlin.String? = null,
    @SerialName(value = "status")
    val status: kotlin.Int? = null,
    @SerialName(value = "detail")
    val detail: kotlin.String? = null,
    @SerialName(value = "instance")
    val instance: kotlin.String? = null
) : kotlin.collections.HashMap<String, kotlin.String>
```

**Comment by cromefire** [comment]
Did you test this against a real Api? (so that it's working and not only compiling and generating runtime errors) If so I can probably safely merge this

**Comment by cromefire** [comment]
> You didn't handle decoding of mixed stuff yet, right?
> 
> I've seen classes, where it generated something like (simplified; out of my memory)
> 
> ```kotlin
> data class Xyz(val test: String) : List<Int>
> ```

This should be irrelevant in this case though

**Review by cromefire — APPROVED** [review]
Fine, if you tested that it works at runtime

**Comment by fullkomnun** [comment]
I have tested it and it works =]

**Pull request merged**
