### PR TITLE
.kt file names should start with a capital letter

### PR DESCRIPTION
**Pull request by fullkomnun**
just fixed casing of a few generated infrastructure .kt source files

### CODE REVIEW

**Comment by cromefire** [comment]
The pascal case convention only applies to classes not plain files that don't contain a class. For those I'm going with the same convention that official libraries go with.

**Comment by cromefire** [comment]
Sample: https://github.com/Kotlin/kotlinx-datetime/blob/master/core/common/src/math.kt

**Comment by fullkomnun** [comment]
Seems weird but if that is what the standard library does than so be it =]

**Comment by cromefire** [comment]
Well I like that convention many languages have the files in lower case, java does pascal case because they have the same name than the class, so I think it makes sense to have it be a separate case

**Pull request closed without merging**
